# SwiftLint configuration for Swift 6
# Optimized for modern Swift with strict concurrency

# Paths to include/exclude
included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - DerivedData
  - Package.swift

# Rules configuration
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # We want to keep TODOs
  - force_cast # Sometimes necessary
  - force_try # Sometimes necessary in tests
  - line_length # Handled by SwiftFormat
  - file_length # Large files can be okay
  - type_body_length # Some types are naturally large
  - function_body_length # Some functions are naturally large
  - cyclomatic_complexity # Can be too restrictive
  - large_tuple # Tuples are fine in Swift
  - multiple_closures_with_trailing_closure # Swift 5.3+ handles this well
  - no_fallthrough_only # Fallthrough can be useful
  - function_parameter_count # Some functions need many parameters
  - identifier_name # We need to match Bubble Tea API names
  - no_extension_access_modifier # Extensions are useful for organization
  - no_grouping_extension # Extensions help organize code
  - type_contents_order # We have specific organization needs

# Rule configuration
analyzer_rules:

identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - id
    - ID
    - i
    - j
    - k
    - x
    - y
    - z
    - n
    - m
    - vm
    - vc
    - to
    - up
    - go
    - on
    - of

type_name:
  min_length: 3
  max_length: 60
  excluded:
    - ID
    - Cmd
    - Msg
    - UI
    - VM
    - VC

nesting:
  type_level: 3
  function_level: 5

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

file_header:
  forbidden_pattern: '^\/\/\n\/\/  .*?\.swift\n\/\/  .*\n\/\/\n\/\/  Created by .* on .*\.\n\/\/  Copyright © .* All rights reserved\.\n\/\/$'

custom_rules:
  swift6_sendable:
    name: "Swift 6 Sendable"
    message: "Consider marking types that cross concurrency boundaries as Sendable"
    regex: "(public |internal )?(struct|class|enum) [A-Z][a-zA-Z0-9]*(?!.*: .*Sendable)"
    match_kinds:
      - keyword
    severity: warning

  async_await_consistency:
    name: "Async/Await Consistency"
    message: "Use async/await consistently instead of completion handlers"
    regex: 'completion:\s*\((.*?)\)\s*->\s*Void'
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"