# SwiftLint configuration for Matcha
# Swift 6 compatible configuration

# Included/Excluded paths
included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - Package.swift
  - .git
  - DerivedData

# Rule Configuration
analyzer_rules:
  - unused_declaration
  - unused_import

# Enabled Rules
opt_in_rules:
  # Performance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_into

  # Style
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - empty_enum_arguments
  - explicit_init
  - file_header
  - file_name_no_space
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

  # Swift 6 / Concurrency
  - discouraged_optional_collection
  - explicit_self

# Disabled Rules
disabled_rules:
  - todo
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - multiple_closures_with_trailing_closure
  - identifier_name
  - nesting
  - opening_brace
  - switch_case_alignment

# Rule Configuration
attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@discardableResult"
    - "@MainActor"
    - "@Sendable"

closure_body_length:
  warning: 50
  error: 100

collection_alignment:
  align_colons: true

colon:
  flexible_right_spacing: true
  apply_to_dictionaries: true

explicit_type_interface:
  excluded:
    - local
    - closure

file_name_no_space:
  excluded:
    - "Package.swift"

force_cast:
  severity: warning

force_try:
  severity: warning

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  max_length: 50
  allowed_symbols: "_"
  validates_start_with_lowercase: true
  excludes:
    - id
    - x
    - y
    - z

indentation_width:
  indentation_width: 4

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: false
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

nesting:
  type_level: 2
  statement_level: 5

trailing_comma:
  mandatory_comma: false

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length: 50

unused_optional_binding:
  ignore_optional_try: false

vertical_whitespace:
  max_empty_lines: 2

# Custom Rules
custom_rules:
  discouraged_force_unwrap:
    regex: "!"
    match_kinds:
      - "source.lang.swift.literal.boolean"
    excluded: "Tests"
    message: "Avoid force unwrapping"
    severity: warning

  missing_mark_comment:
    regex: "^// MARK: -?$"
    message: "MARK comments should have descriptive text"
    severity: warning

  prefer_swift_6_concurrency:
    regex: "DispatchQueue|NSLock|NSRecursiveLock|NSConditionLock|NSCondition|pthread"
    message: "Prefer Swift 6 concurrency (async/await, actors) over GCD and locks"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"